version: '3'

services:
  teste-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
    volumes:
      - ./dev_db_persitence:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network


networks: 
  postgres-compose-network:
    driver: bridge