on: push

jobs:
  format:
    runs-on: ubuntu-latest
    name: lint
    strategy:
      matrix:
        otp: ["24.2.1"]
        elixir: ["1.13.3"]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix format --check-formatted

  credo:
    runs-on: ubuntu-latest
    name: credo
    strategy:
      matrix:
        otp: ["24.2.1"]
        elixir: ["1.13.3"]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix credo

  test:
    runs-on: ubuntu-latest
    name: tests
    services:
      postgres:
        image: postgres
        env: 
          POSTGRES_PASSWORD: root
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      matrix:
        otp: ["24.2.1"]
        elixir: ["1.13.3"]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix test
      - env:
          POSTGRES_HOST: postgres
